---
- name: Install APT Packages
  apt:
    name: "{{item}}"
    state: present
  with_items: "{{deb_local_packages}}"
  become: true
  delegate_to: 127.0.0.1

- name: Install PIP Packages
  pip:
    name: "{{ item }}"
    state: present
  with_items: "{{ pip_local_packages }}"
  delegate_to: 127.0.0.1
  become: true

- name: Create files directory in load-test-images role if not present
  file:
    path: "{{ playbook_dir }}/roles/load-test-images/files"
    state: directory
    mode: 0755

- name: Check for available image tarballs 
  shell: ls *.tar
  args:
    chdir: "{{ playbook_dir }}/roles/load-test-images/files"
  register: tar
  delegate_to: 127.0.0.1

- name: Fetch test images from dockerhub 
  docker_image: 
    name: "{{item.image}}:{{item.tag}}"
    state: present
    pull: true
    force: yes
  register: result
  until: "'Pulled image' and item.image in result.actions[0]"
  delay: 60
  retries: 3  
  when: "item.label ~ '_' ~ item.tag ~ '.tar' not in tar.stdout_lines"
  with_items: "{{ test_images }}"
  become: true

- name: Create TAR files for test images
  shell: >
    docker save {{item.image}}:{{item.tag}}
    -o {{item.label}}_{{item.tag}}.tar
  args:
    chdir: "{{playbook_dir}}/roles/load-test-images/files"
    creates: "{{item.label}}_{{item.tag}}.tar"
  become: true
  with_items: "{{ test_images }}"

- name: Get current user details
  command: whoami
  register: user

- name: Change permissions of tarfile 
  file:
    path: "{{playbook_dir}}/roles/load-test-images/files"
    owner: "{{ user.stdout }}"
    group: "{{ user.stdout }}"
    recurse: true
  become: true 

- name: Remove test images from localhost
  docker_image:
    name: "{{item.image}}:{{item.tag}}" 
    state: absent
  with_items: "{{ test_images }}"
  become: true
  


