#!/bin/bash
set -e

IMAGEID=$( docker images -q openebs/operator )

if [ ! -z "${DNAME}" ] && [ ! -z "${DPASS}" ]; 
then 
  docker login -u "${DNAME}" -p "${DPASS}"; 
  #Push to docker hub repository with latest tag
  docker tag ${IMAGEID} openebs/operator:latest
  docker push openebs/operator:latest; 
else
  echo "No docker credentials provided. Skip uploading openebs/operator:latest to docker hub"; 
fi;
