# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

BOX_MODE_OPENEBS    = 1
BOX_MODE_KUBERNETES = 2

box_Mode=ENV['OPENEBS_BUILD_BOX'] || 2

Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  if ((box_Mode.to_i < BOX_MODE_OPENEBS.to_i) || (box_Mode.to_i > BOX_MODE_KUBERNETES.to_i))
    puts "Invalid value set for OPENEBS_BUILD_BOX."
    puts "Usage: OPENEBS_BUILD_BOX=1 for OpenEBS."
    puts "Usage: OPENEBS_BUILD_BOX=2 for Kubernetes."
    puts "Defaulting to OpenEBS..."
    puts "Do you want to continue?(y/n):"

    input = STDIN.gets.chomp
    while 1 do
      if(input == "n")
        Kernel.exit!(0)
      elsif(input == "y")
        break
      else
        puts "Invalid input: type 'y' or 'n'"
        input = STDIN.gets.chomp
      end
    end

    box_Mode = 1
  end

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  config.vm.box_check_update = false

  # Needed for ubuntu/xenial64 packaged boxes
  # The default user is ubuntu for those boxes
  config.ssh.username = "ubuntu"
  config.vm.provision "shell", inline: <<-SHELL
    echo "ubuntu:ubuntu" | sudo chpasswd
  SHELL

  if box_Mode.to_i == BOX_MODE_KUBERNETES.to_i
    config.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--uartmode1", "file", File.join(Dir.pwd, "k8s-console.log")]
    end
    config.vm.box = "openebs/k8s-1.7"
  elsif box_Mode.to_i == BOX_MODE_OPENEBS.to_i
    config.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--uartmode1", "file", File.join(Dir.pwd, "openebs-console.log")]
    end
    config.vm.box = "ubuntu/xenial64"
  end
end
