# libiscsi.yml
#Description: Including libiscsi compliance test to OpenEBS e2e suite.

###############################################################################################
#Test Steps:
#1. Install the packages and dependencies.
#2. Copy the test artifacts to k8s master.
#3. Create a storage volume
#4. Obtain the IP address of the controller pod.
#5. Copy the libsiscsi test packages to the minion.
#6. Discover the volume from one of the K8s nodes.
#7. Run libiscsi test suite.
#8. Generate the test summary.
#9. Perform test cleanup.
###############################################################################################

---
- hosts: localhost

  vars_files:
    - libiscsi-vars.yml

  tasks:
   - block:

       - name: 1) Install the prerequisites
         include: libiscsi-prerequisites.yml

       - name: 2) Copy the volume claim to kube master
         copy:
           src: "{{ volume_def }}"
           dest: "{{ result_kube_home.stdout }}"
         delegate_to: "{{ groups['kubernetes-kubemasters'].0 }}"

       - name: 3) Create test specific namespace
         command: kubectl create ns {{ namespace }}
         delegate_to: "{{groups['kubernetes-kubemasters'].0}}"

       - name: 3a) Create a storage volume via a pvc
         shell: source ~/.profile; kubectl apply -f "{{ volume_def }}" -n {{ namespace }}
         args:
           executable: /bin/bash
         delegate_to: "{{ groups['kubernetes-kubemasters'].0 }}"

       - name: 3b) Confirm volume container is running
         shell: source ~/.profile; kubectl get pods -n {{ namespace }} | grep pvc | grep {{item}} | grep Running | wc -l
         args:
           executable: /bin/bash
         register: result
         until: result.stdout|int >= 1
         delay: 30
         retries: 10
         with_items:
           - ctrl
           - rep
         delegate_to: "{{ groups['kubernetes-kubemasters'].0 }}"

       - name: 4) Get storage ctrl pod name
         shell: source ~/.profile; kubectl get pods -n {{ namespace }} | grep ctrl
         args:
           executable: /bin/bash
         register: ctrl_name
         delegate_to: "{{ groups['kubernetes-kubemasters'].0 }}"

       - name: 4a) Set ctrl pod name to variable
         set_fact:
           ctrl_pod_name: "{{ ctrl_name.stdout.split()[0] }}"

       - name: 4b) Get IP address of ctrl pod
         shell: source ~/.profile; kubectl describe pod {{ ctrl_pod_name }} -n {{ namespace }} | grep IP
         args:
           executable: /bin/bash
         register: ctrl_IP
         delegate_to: "{{groups['kubernetes-kubemasters'].0}}"

       - name: 4c) Set IP of Pod to variable
         set_fact:
           ctrl_ip: "{{ ctrl_IP.stdout_lines[0].split()[1]}}"

       - name: 5) Get $HOME of K8s minion for kubernetes user
         shell: source ~/.profile; echo $HOME
         args:
           executable: /bin/bash
         register: result_kube_home
         delegate_to: "{{groups['kubernetes-kubeminions'].0}}"

       - name: 5a) Copy libiscsi test list into kube minion
         copy:
           src: "{{ test_list }}"
           dest: "{{ result_kube_home.stdout }}"
         delegate_to: "{{ groups['kubernetes-kubeminions'].0 }}"

       - name: 6) Discover the iSCSI target using iscsi-ls
         shell: iscsi-ls iscsi://{{ ctrl_ip }}
         register: target
         delegate_to: "{{ groups['kubernetes-kubeminions'].0 }}"
         until: "result.rc == 0"
         delay: 10 
         retries: 12
         tags:
           - skip_ansible_lint

       - name: 6a) Set target iqn to variable
         set_fact:
           iqn: "{{ target.stdout.split()[0] | regex_replace('Target:','')}}"

       - name: 6b) Create log directory for libiscsi test run
         file:
           path: "{{ result_kube_home.stdout }}/libiscsi_suite_logs"
           state: directory
         delegate_to: "{{ groups['kubernetes-kubeminions'].0 }}"

       - name: 6c) Get test list from test file
         command: cat {{ result_kube_home.stdout }}/{{ test_list }}
         register: tests
         delegate_to: "{{ groups['kubernetes-kubeminions'].0 }}"

       - name: 7) Run the libiscsi test suites
         shell: >
           iscsi-test-cu --test={{ item }}
           iscsi://{{ ctrl_ip }}/{{ iqn }}/0
           --dataloss --allow-sanitize
           > {{ result_kube_home.stdout }}/libiscsi_suite_logs/{{ item }}.log
           2>&1
         args:
           executable: /bin/bash
         delegate_to: "{{ groups['kubernetes-kubeminions'].0 }}"
         with_items: "{{ tests.stdout_lines }}"
         ignore_errors: true

       - name: 8) Generate test summary
         script: parse.sh {{ result_kube_home.stdout }}/libiscsi_suite_logs
         delegate_to: "{{ groups['kubernetes-kubeminions'].0 }}"
         register: summary

       - name: 8a) Display the test status
         debug:
           msg: "{{ summary.stdout }}"

       - name: Test Passed
         set_fact:
           flag: "Test Passed"
           status_id: 1

       - name: Set Status
         set_fact:
           status: "good"

     rescue:
       - name: Test Failed
         set_fact:
           flag: "Test Failed"
           status_id: 5

       - name: Set Status
         set_fact:
           status: "danger"

     always:
       - block:

           - include: libiscsi-cleanup.yml

           - name: Test Cleanup Passed
             set_fact:
               cflag: "Cleanup Passed"

         rescue:
           - name: Test Cleanup Failed
             set_fact:
               cflag: "Cleanup Failed"

         always:

           - include_tasks: "{{ansible_env.HOME}}/{{utils_path}}/stern_task.yml"
             vars:
               status: stop

           - name: Update Testrail
             shell: source ~/.profile; python3 {{ inventory_dir | dirname }}/files/updater.py -tuser {{ testrail_user }} -tpass {{ testrail_password }} -sid {{ test_suite_id }} -cid {{ test_case_id }} -stid {{ status_id }}
             args:
               executable: /bin/bash

           - name: Testrail Updated
             set_fact:
               tflag: "Testrail Updated"

         rescue:
           - name: Testrail Update failed
             set_fact:
               tflag: "Testrail Update Failed"

           - name: Send slack notification
             slack:
               token: "{{ lookup('env','SLACK_TOKEN') }}"
               msg: '{{ ansible_date_time.time }} TEST: {{test_name}}, RESULT: {{ flag }},{{ cflag }},{{tflag}}'
               color: "{{status}}"
             when: slack_notify | bool and lookup('env','SLACK_TOKEN')

