{{- if .Values.policies.monitoring.enabled }}
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: openebs-grafana
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  name: openebs-grafana
{{- if .Values.rbacEnable }}
  namespace: {{ .Values.rbac.namespace }}
{{- end }}
spec:
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: openebs-grafana
    spec:
      serviceAccountName: {{ .Values.operator.name }}
      containers:
      - image: grafana/grafana:4.5.2
        name: grafana
        ports:
        - containerPort: 3000
        env:
          - name: GF_AUTH_BASIC_ENABLED
            value: "true"
          - name: GF_AUTH_ANONYMOUS_ENABLED
            value: "false"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          timeoutSeconds: 1
{{- end }}
