name: Release Charts
on:
  push:
    paths:
      - 'charts/**'
    branches:
      - develop
      - "release/**"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
          
      - name: Block publish if version is a develop pre-release
        run: |
          VERSION=$(yq '.version' charts/Chart.yaml)
          if [[ "$VERSION" == *-develop* ]]; then
            echo "Chart version is a develop prerelease: $VERSION"
            echo "Aborting chart release on a release branch"
            exit 1
          fi

      - name: Publish openebs develop or prerelease umbrella helm chart
        uses: stefanprodan/helm-gh-pages@v1.7.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: .
