name: GitMod Update
run-name: ${{ inputs.run-name }}
on:
  workflow_dispatch:
    inputs:
      run-name:
        description: 'The distinct run name used to retrieve the run ID. Defaults to the workflow name'
        type: string
        required: false

jobs:
  submodule:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          submodules: recursive
      - id: nixpath
        run: echo "nix_path=nixpkgs=$(jq -r '.nixpkgs.url' nix/sources.json)" >> $GITHUB_OUTPUT
      - uses: cachix/install-nix-action@v31.11.0
        with:
          nix_path: "${{ steps.nixpath.outputs.nix_path }}"
      - name: Prefetch Nix-Shell
        run: nix-build ./scripts/helm/shell.nix
      - name: Update submodules
        run: ./scripts/git/set-submodule-branches.sh -u
      - name: Generate image list
        run: nix-shell ./scripts/helm/shell.nix --run "./scripts/helm/images.sh generate --dependency-update"
      - name: Patch chart/Chart.yaml
        run: nix-shell ./scripts/helm/shell.nix --run "./scripts/helm/images.sh patch"
      - name: Update chart README.md
        run: nix-shell ./scripts/helm/shell.nix --run "SKIP_GIT=1 ./scripts/helm/generate-readme.sh"
      - id: set-target
        run: |
          version=$(nix-shell -p yq-go --run "yq '.appVersion' charts/Chart.yaml")
          echo "branch=ci-bot/mod-update/${version}" >> $GITHUB_OUTPUT
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v8
        with:
          commit-message: "chore(ci): update git submodules"
          title: "[CI] Update git submodules"
          draft: false
          signoff: true
          delete-branch: true
          branch: ${{ steps.set-target.outputs.branch }}
          token: ${{ secrets.ORG_CI_GITHUB }}
      - name: Approve Pull Request by CI Bot
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          gh pr review ${{ steps.cpr.outputs.pull-request-number }} --approve
        env:
          GH_TOKEN: ${{ github.token }}

  chart-images:
    needs: submodule
    if: ${{ needs.submodule.outputs.pull-request-number == '' }}
    uses: ./.github/workflows/chart-images.yml
    secrets: inherit

  release-chart:
    needs: chart-images
    secrets: inherit
    uses: ./.github/workflows/chart-release.yml
