name: Build image
on:
  pull_request_target:
    branches:
      - develop
      - 'release/**'
jobs:
  image-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: DeterminateSystems/nix-installer-action@v11
        with:
          kvm: false
      - uses: DeterminateSystems/magic-nix-cache-action@v6
      - name: Test building the static binaries
        run: nix-build -A utils.debug.x86_64.linux-musl.kubectl-openebs --arg incremental false

