name: Pull Request
on:
  pull_request:
    branches:
      - develop
      - "release/**"

env:
  CI: 1

jobs:
  markdown-spell-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v14
      - name: Pre-populate nix-shell
        run: |
          export NIX_PATH=nixpkgs=$(jq '.nixpkgs.url' nix/sources.json -r)
          echo "NIX_PATH=$NIX_PATH" >> $GITHUB_ENV
      - name: Run spell check
        run: nix-shell -p codespell --run "git ls-files '*.md' | xargs codespell --ignore-words '.codespell-ignores.txt'"

  update-chart-script-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - uses: cachix/install-nix-action@v22
      - name: Pre-populate nix-shell
        run: |
          export NIX_PATH=nixpkgs=$(jq '.nixpkgs.url' nix/sources.json -r)
          echo "NIX_PATH=$NIX_PATH" >> $GITHUB_ENV
          nix-shell --pure --run "echo" ./shell.nix

      - name: Test the chart version updater script
        run: |
          nix-shell --pure --run "./scripts/helm/test-update-chart-version.sh" ./shell.nix
