name: Trivy Check CI

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 3 1,15 * *'

permissions:
  contents: read
  security-events: write
  actions: read

env:
  CI: 1

jobs:
  helm-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: cachix/install-nix-action@v31.11.0

      - name: Pre-populate nix-shell
        run: |
          export NIX_PATH=nixpkgs=$(jq '.nixpkgs.url' nix/sources.json -r)
          echo "NIX_PATH=$NIX_PATH" >> $GITHUB_ENV
          nix-shell --pure --run "echo" ./shell.nix

      - name: Helm dependency update
        working-directory: charts
        run: nix-shell shell.nix --run "helm dependency update ."

      - name: Render Helm Templates
        working-directory: charts
        run: |
          CHART_NAME=$(yq '.name' Chart.yaml)
          RELEASE_NAME=${RELEASE_NAME:-$CHART_NAME}
          nix-shell shell.nix --run \
            "helm template \"$RELEASE_NAME\" . > rendered.yaml"

      - name: Trivy Helm Misconfiguration Scan
        uses: aquasecurity/trivy-action@v0.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          scan-type: config
          scan-ref: charts/rendered.yaml
          format: sarif
          output: trivy-helm.sarif
          severity: HIGH,CRITICAL

      - name: Upload Helm SARIF
        uses: github/codeql-action/upload-sarif@v4.37.3
        with:
          sarif_file: trivy-helm.sarif
          category: trivy-helm

  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      images: ${{ steps.set-matrix.outputs.images }}

    steps:
      - uses: actions/checkout@v7
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - uses: cachix/install-nix-action@v31.11.0

      - name: Pre-populate nix-shell
        run: |
          export NIX_PATH=nixpkgs=$(jq '.nixpkgs.url' nix/sources.json -r)
          echo "NIX_PATH=$NIX_PATH" >> $GITHUB_ENV
          nix-shell --pure --run "echo" ./scripts/helm/shell.nix

      - name: Generate image list
        run: |
          nix-shell ./scripts/helm/shell.nix --run "./scripts//helm/images.sh generate --dependency-update --exit-code"

      - id: set-matrix
        run: |
          images=$(jq -R -s -c 'split("\n") | map(select(length > 0))' charts/images.txt)
          echo "images=$images" >> "$GITHUB_OUTPUT"

  image-scan:
    needs: generate-matrix
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        image: ${{ fromJson(needs.generate-matrix.outputs.images) }}

    steps:
      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@v0.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          scan-type: image
          scan-ref: ${{ matrix.image }}
          format: sarif
          output: trivy-image.sarif
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          scanners: vuln
          cache: true

      - name: Upload Image SARIF
        uses: github/codeql-action/upload-sarif@v4.37.3
        with:
          sarif_file: trivy-image.sarif
          category: trivy-image-${{ matrix.image }}
